import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import IndicatorBar from '@/components/IndicatorBar';
import NavbarWrapper from '@/components/NavbarWrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'netflix-clone',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col items-center justify-center w-full min-h-screen bg-white`}
      >
        <div className="min-h-screen bg-black w-[375px]">
          {children}
          <NavbarWrapper />
          <IndicatorBar />
        </div>
      </body>
    </html>
  );
}
