import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import IndicatorBar from '@/components/IndicatorBar';
import NavbarWrapper from '@/components/NavbarWrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'netflix-clone',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col items-center justify-center w-full min-h-screen bg-white`}
      >
        <div className="relative w-[375px] min-h-screen bg-black mx-auto">
          <main className="pb-[96px]">{children}</main> {/* 하단 UI 높이만큼 패딩 */}
          <div className="absolute bottom-0 left-0 w-full">
            <IndicatorBar />
            <NavbarWrapper />
          </div>
        </div>
      </body>
    </html>
  );
}
