import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import IndicatorBar from "@/components/IndicatorBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "netflix-clone",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col items-center justify-center min-h-screen bg-white relative`}
      >
        {/* 휴대폰 프레임 */}
        <div className="w-[390px] h-[700px] rounded-[40px] shadow-[0_20px_60px_rgba(0,0,0,0.6)] overflow-hidden pb-5">
          {children}
          <IndicatorBar />
        </div>
      </body>
    </html>
  );
}
